# MCF8316 BLDC MOTOR DRIVER EXAMPLE
#
# Please modify this configuration to suit your needs.
esphome:
  name: mcf8316-example
  friendly_name: MCF8316 Example
  min_version: "2025.8.4"

esp32:
  board: lolin_s2_mini  # Change this for the board you are using
  framework:
    type: esp-idf

logger:

# Set up a WiFi access point and web server for this example.
# After connecting to the access point, open http://192.168.4.1/ in a web browser
# to access the user interface.
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  ap:
    ssid: "mcf8316-example"
    password: "JustForTesting"
    ap_timeout: 1s
  power_save_mode: light
web_server:
  local: true
  log: true
  ota: false
  version: 3

# Import the MCF8316 component.
external_components:
  # Import the component from Github.
  # - source: github://brown-studios/esphome-mcf8316@main
  #   components: [ mcf8316 ]
  # Import the component from a local directory.
  - source: components

# Configure the I2C bus.
i2c:
  - scl: 9
    sda: 8
    scan: false  # The MCF8316 will not be detected in a scan although it is harmless
    frequency: 100kHz

# Configure the BLDC motor driver.
mcf8316:
  - id: motor_driver
    wake: 2
    nfault: 3

# Controls
button:
  - platform: template
    name: "Read config"
    on_press:
      then:
        - lambda: |-
            auto driver = id(motor_driver);
            driver->read_config();
  - platform: template
    name: "Configure"
    on_press:
      then:
        - lambda: |-
            auto driver = id(motor_driver);
            auto config = driver->make_default_config();

            // NOTE: Creating a motor configuration from scratch requires setting many
            // parameters as described in the MCF8316 datasheet.  This example just shows the
            // syntax and isn't enough to get the motor running.  For a real implementation,
            // see https://github.com/brown-studios/minuet-firmware/blob/main/minuet/fan_driver.h

            config.set(esphome::mcf8316::FG_DIV, esphome::mcf8316::fg_div_from_motor_poles(4));
            // config.set...

            driver->write_config(config);
  - platform: template
    name: "Start MPET"
    on_press:
      then:
        - lambda: |-
            auto driver = id(motor_driver);
            driver->start_mpet(false);
  - platform: template
    name: "Start motor"
    on_press:
      then:
        - lambda: |-
            auto driver = id(motor_driver);
            driver->write_speed_input(10);
  - platform: template
    name: "Stop motor"
    on_press:
      then:
        - lambda: |-
            auto driver = id(motor_driver);
            driver->write_speed_input(0);
  - platform: template
    name: "Clear fault"
    on_press:
      then:
        - lambda: |-
            auto driver = id(motor_driver);
            driver->clear_fault();
